# Generated by Django 4.1.1 on 2022-09-19 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_time', models.CharField(max_length=200)),
                ('informacoes', models.TextField()),
                ('numero_titulos', models.IntegerField()),
                ('historio', models.CharField(max_length=100)),
                ('divisao', models.CharField(max_length=50)),
                ('ano_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
