# Generated by Django 4.1.1 on 2022-09-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita',
            new_name='Futebol',
        ),
    ]
