# Generated by Django 4.1.1 on 2022-09-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('futebol', '0002_rename_receita_futebol'),
    ]

    operations = [
        migrations.AddField(
            model_name='futebol',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
            preserve_default=False,
        ),
    ]
