# Generated by Django 4.1.1 on 2022-09-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0004_futebol_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='futebol',
            name='foto_time',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
